[package]
name = "roll-rs"
version = "0.1.0"
authors = ["Diana Thayer <garbados@gmail.com>"]
edition = "2018"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
regex = "1"
